root: ./

redirects:
    security: contributors/how-can-i-help/security/README.md
    guides/developer/quick-start: development-docs.md
    guides/developer-guides/rest-api/: development-docs.md
    guides/developer/mobile-apps/whitelabeling-mobile-apps: development-docs.md
    guides/apps-development/getting-started: development-docs.md
    guides/bots/create-and-run-a-bot/hubot-bot: development-docs.md
    guides/administration/administration/identity-management-ee-vs-ce: guides/administration/identity-management-ee-vs-ce.md
    apps-development/getting-started: development-docs.md
    api/rest-api: development-docs.md
    guides/administration/settings/ldap: guides/administration/admin-panel/settings/ldap/README.md
    guides/administration/admin-panel/settings/ldap/user-search-settings: guides/administration/admin-panel/settings/ldap/README.md
    installation/manual-installation/centos: quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/rocket.chat-in-centos.md
    administrator-guides/integrations/zapier/using-zaps: guides/administration/admin-panel/integrations/zapier.md
    installation/docker-containers/docker-compose: quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/README.md
    developer-guides/rest-api: development-docs.md
    developer-guides/rest-api/authentication/login: development-docs.md
    developer-guides/realtime-api: development-docs.md
    guides/administration/settings/video-conference-admin-guide/omnichannel-video-audio-call-admins-guide: guides/rocket.chat-conference-call/omnichannel-video-audio-call-admins-guide.md
    developer-guides/mobile-apps/supporting-ssl: development-docs.md
    developer-guides: development-docs.md
    guides/administration/settings/omnichannel-admins-guide: guides/administration/admin-panel/settings/omnichannel-admins-guide/README.md
    quick-start/installing-and-updating/paas-deployments/aws-marketplace: quick-start/installing-and-updating/paas-deployments/aws.md
    guides/administration/administration/settings/canned-responses-rocket.chat-admins-guides: guides/omnichannel/canned-responses/canned-responses-rocket.chat-admins-guides.md
    developer-guides/iframe-integration/authentication: development-docs.md
    developer-guides/rest-api/chat/postmessage: development-docs.md
    api/rest-api/personal-access-tokens: development-docs.md
    developer-guides/livechat-api: development-docs.md
    developer-guides/rest-api/im: development-docs.md
    developer-guides/rest-api/authentication: development-docs.md
    guides/omnichannel-guides/omnichannel-manger-guides: guides/omnichannel/managers.md
    quick-start/installing-and-updating/docker-containers/docker-compose: quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/README.md
    developer-guides/developing-apps/getting-started: development-docs.md
    developer-guides/rest-api/channels/cleanhistory: development-docs.md
    developer-guides/rest-api/channels/info: development-docs.md
    developer-guides/rest-api/livechat/sms-incoming: development-docs.md
    guides/administration/settings/account-settings: guides/administration/admin-panel/settings/account-settings/README.md
    guides/developer/iframe-integration/authentication/testing-the-iframe-authentication: development-docs.md
    installation/manual-installation/centos/: quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/rocket.chat-in-centos.md
    installation/paas-deployments/heroku: quick-start/installing-and-updating/introduction/choosing-a-deployment-method.md
    installing-and-updating/manual-installation/centos: quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/rocket.chat-in-centos.md
    developer-guides/quick-start: development-docs.md
    api/rest-api/methods/chat/sendmessage: development-docs.md
    developer-guides/mobile-apps: development-docs.md
    developer-guides/realtime-api/subscriptions: development-docs.md
    api/rest-api/methods/subscriptions/read: development-docs.md
    api/rest-api/methods/users/create: development-docs.md
    developer-guides/realtime-api/method-calls/login: development-docs.md
    developer-guides/realtime-api/method-calls/login/: development-docs.md
    developer-guides/rest-api/im: development-docs.md
    developer-guides/rest-api/livechat: development-docs.md
    installation/manual-installation/centos/: quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/rocket.chat-in-centos.md
    guides/developer/iframe-integration/authentication/testing-the-iframe-authentication: development-docs.md
    quick-start/installing-and-updating/manual-installation/centos: quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/rocket.chat-in-centos.md
    user-guides/voice-and-video-calls: guides/rocket.chat-conference-call/conference-call-users-guide.md
    developer-guides/deeplink: development-docs.md
    developer-guides/rest-api/users/info: development-docs.md
    api/realtime-api/subscriptions/stream-notify-room: development-docs.md
    api/rest-api/methods/chat/getthreadslist: development-docs.md
    api/rest-api/methods/users/create: development-docs.md
    guides/administration/administration/settings/email/direct-reply: guides/administration/admin-panel/settings/email/direct-reply.md
    administrator-guides/setting-up-video-conferencing: guides/rocket.chat-conference-call/conference-call-admin-guide/README.md
    api/realtime-api: development-docs.md
    api/realtime-api/method-calls: development-docs.md
    api/realtime-api/method-calls/logout: development-docs.md
    guides/administration/administration/settings/ldap: guides/administration/admin-panel/settings/ldap/README.md
    developer-guides/ui-and-theming: development-docs.md
    developer-guides/branches-and-releases: development-docs.md
    developer-guides/rest-api/im/list: development-docs.md
    developer-guides/rest-api/integration: development-docs.md
    developer-guides/rest-api/miscellaneous/spotlight: development-docs.md
    developer-guides/rest-api/rate-limiter/: development-docs.md
    developer-guides/rest-api/rooms/upload: development-docs.md
    developer-guides/rest-api/subscriptions/get: development-docs.md
    developer-guides/ui-and-theming: development-docs.md
    guides/administration/admin-panel/settings/ldap/user-search-settings: guides/administration/admin-panel/settings/ldap/README.md
    
    


