root: ./

redirects:  
    security: contributors/contributing/security/README.md
    guides/developer/quick-start: development-docs.md
    guides/developer-guides/rest-api/: development-docs.md 
    guides/developer/mobile-apps/whitelabeling-mobile-apps: development-docs.md 
    guides/apps-development/getting-started: development-docs.md
    guides/bots/create-and-run-a-bot/hubot-bot: development-docs.md
    apps-development/getting-started: development-docs.md
    api/rest-api: development-docs.md    
